<% raise NotImplementedError, "Sorry, the 'default' theme is broken, please try using 'bridgepdx' and run 'rake bridgepdx:styles' to download the latest styles. See themes/README.txt for information on how to set the current theme." %>

# Organization running event:
organization: 'Ignite Anytown'

# Aggreement to show on proposal pages.
agreement: 'I understand that my talk may be recorded and posted online for the whole world to see. I understand that Ignite Anytown is not the appropriate place for commercial promotion ("spam") of a product, service or solution and this not welcomed by the audience.'

# Breadcrumbs that are always visible, each breadcrumb is a name and URI:
breadcrumbs:
  - ['Ignite Anytown', 'http://www.igniteanytown.com/']
  - ['Proposals', '/proposals/']

# Timezone for dates in this application:
timezone: 'Pacific Time (US & Canada)'
